from types import TracebackType
from typing import Protocol

from pokerman.application.read_models import PlayerLedgerRow, PlayerStatistics
from pokerman.domain.entities import BuyIn, PokerRoom, RoomPlayer, User
from pokerman.domain.value_objects import RoomCode


class UserRepository(Protocol):
    async def get_by_telegram_id(self, telegram_id: int) -> User | None: ...
    async def add(self, user: User) -> User: ...
    async def save(self, user: User) -> None: ...


class RoomRepository(Protocol):
    async def add(self, room: PokerRoom) -> PokerRoom: ...
    async def get_by_id(self, room_id: int) -> PokerRoom | None: ...
    async def get_by_code(self, code: RoomCode) -> PokerRoom | None: ...
    async def get_by_deep_link_token(self, token: str) -> PokerRoom | None: ...
    async def is_code_taken_by_active_room(self, code: RoomCode) -> bool: ...
    async def save(self, room: PokerRoom) -> None: ...
    async def list_for_user(self, telegram_id: int) -> list[PokerRoom]: ...


class RoomPlayerRepository(Protocol):
    async def add(self, member: RoomPlayer) -> RoomPlayer: ...
    async def get(self, room_id: int, user_telegram_id: int) -> RoomPlayer | None: ...
    async def get_by_id(self, room_player_id: int) -> RoomPlayer | None: ...
    async def list_for_room(self, room_id: int) -> list[RoomPlayer]: ...
    async def save(self, member: RoomPlayer) -> None: ...


class BuyInRepository(Protocol):
    async def add(self, buy_in: BuyIn) -> BuyIn: ...
    async def get_by_id(self, buy_in_id: int) -> BuyIn | None: ...
    async def save(self, buy_in: BuyIn) -> None: ...
    async def list_pending_for_room(self, room_id: int) -> list[BuyIn]: ...
    async def list_for_room_player(self, room_player_id: int) -> list[BuyIn]: ...


class RoomCodeGenerator(Protocol):
    async def generate_unique_code(self) -> RoomCode: ...


class RoomLedgerQuery(Protocol):
    async def player_totals(self, room_id: int) -> list[PlayerLedgerRow]: ...


class PlayerStatisticsQuery(Protocol):
    async def get_statistics(self, telegram_id: int) -> PlayerStatistics: ...


class UnitOfWork(Protocol):
    @property
    def users(self) -> UserRepository: ...

    @property
    def rooms(self) -> RoomRepository: ...

    @property
    def room_players(self) -> RoomPlayerRepository: ...

    @property
    def buy_ins(self) -> BuyInRepository: ...

    async def __aenter__(self) -> "UnitOfWork": ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
