"""add room player cash out fields

Revision ID: 49be5dc1801b
Revises: 7e866075f23a
Create Date: 2026-08-23 02:40:20.775337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49be5dc1801b'
down_revision: Union[str, Sequence[str], None] = '7e866075f23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_players', sa.Column('final_chip_count', sa.Integer(), nullable=True))
    op.add_column('room_players', sa.Column('cashed_out_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_players', 'cashed_out_at')
    op.drop_column('room_players', 'final_chip_count')
    # ### end Alembic commands ###
