"""initial schema

Revision ID: 7e866075f23a
Revises: 
Create Date: 2026-08-21 20:31:13.927458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e866075f23a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('poker_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('deep_link_token', sa.String(), nullable=False),
    sa.Column('default_buy_in_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', name='room_status'), nullable=False),
    sa.Column('qr_file_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deep_link_token', name='uq_poker_rooms_deep_link_token')
    )
    op.create_index('ix_poker_rooms_active_code', 'poker_rooms', ['code'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('room_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['poker_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_telegram_id', name='uq_room_players_room_user')
    )
    op.create_table('buy_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_player_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='buy_in_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_telegram_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['room_player_id'], ['room_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buy_ins_room_player_status', 'buy_ins', ['room_player_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buy_ins_room_player_status', table_name='buy_ins')
    op.drop_table('buy_ins')
    op.drop_table('room_players')
    op.drop_index('ix_poker_rooms_active_code', table_name='poker_rooms', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('poker_rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
