"""add user personal settings

Revision ID: e9c6184382a3
Revises: 49be5dc1801b
Create Date: 2026-08-23 04:24:52.502804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c6184382a3'
down_revision: Union[str, Sequence[str], None] = '49be5dc1801b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_qr_file_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spending_limit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('spending_limit_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spending_limit_updated_at')
    op.drop_column('users', 'spending_limit')
    op.drop_column('users', 'default_qr_file_id')
    # ### end Alembic commands ###
